const currentUser = {
  id: "current-user",
  name: "Herbert Ngoe",
  username: "herbert",
  avatar: "https://i.pravatar.cc/150?img=12",
};

const recentSearches = [
  "Afrobeats",
  "Cameroon",
  "Technology",
  "Fashion",
  "Football",
];

const suggestedUsers = [
  {
    id: "user-1",
    name: "Sophie Anderson",
    username: "sophiea",
    avatar: "https://i.pravatar.cc/150?img=44",
    bio: "Creative mind • Lifestyle",
    followers: 18400,
    verified: true,
    mutuals: 12,
  },
  {
    id: "user-2",
    name: "James Carter",
    username: "jamesc",
    avatar: "https://i.pravatar.cc/150?img=12",
    bio: "Tech • Travel • Photography",
    followers: 12800,
    verified: false,
    mutuals: 8,
  },
  {
    id: "user-3",
    name: "Olivia Martin",
    username: "oliviam",
    avatar: "https://i.pravatar.cc/150?img=47",
    bio: "Fashion & everyday moments",
    followers: 9700,
    verified: true,
    mutuals: 5,
  },
  {
    id: "user-4",
    name: "Daniel Wilson",
    username: "danielw",
    avatar: "https://i.pravatar.cc/150?img=53",
    bio: "Music • Sports • Culture",
    followers: 24100,
    verified: false,
    mutuals: 15,
  },
  {
    id: "user-5",
    name: "Grace Taylor",
    username: "gracet",
    avatar: "https://i.pravatar.cc/150?img=32",
    bio: "Digital creator • Travel",
    followers: 15600,
    verified: true,
    mutuals: 9,
  },
  {
    id: "user-6",
    name: "Michael Brown",
    username: "mikebrown",
    avatar: "https://i.pravatar.cc/150?img=15",
    bio: "Entrepreneur • Tech enthusiast",
    followers: 8200,
    verified: false,
    mutuals: 4,
  },
  {
    id: "user-7",
    name: "Emma Davis",
    username: "emmad",
    avatar: "https://i.pravatar.cc/150?img=32",
    bio: "Coffee • Music • Good vibes",
    followers: 19400,
    verified: false,
    mutuals: 11,
  },
  {
    id: "user-8",
    name: "Alex Johnson",
    username: "alexj",
    avatar: "https://i.pravatar.cc/150?img=14",
    bio: "Exploring the world one Gist at a time",
    followers: 22100,
    verified: true,
    mutuals: 17,
  },
];

const audioResults = [
  {
    id: "audio-1",
    title: "Calm Down",
    artist: "Rema",
    artwork:
      "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400",
    uses: 1800000,
    duration: "3:39",
    trending: true,
  },
  {
    id: "audio-2",
    title: "Essence",
    artist: "Wizkid",
    artwork:
      "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400",
    uses: 984000,
    duration: "4:08",
    trending: true,
  },
  {
    id: "audio-3",
    title: "Unavailable",
    artist: "Davido",
    artwork:
      "https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=400",
    uses: 742000,
    duration: "2:49",
    trending: true,
  },
  {
    id: "audio-4",
    title: "People",
    artist: "Libianca",
    artwork:
      "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?w=400",
    uses: 528000,
    duration: "2:39",
    trending: false,
  },
  {
    id: "audio-5",
    title: "Love Nwantiti",
    artist: "CKay",
    artwork:
      "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400",
    uses: 412000,
    duration: "3:12",
    trending: false,
  },
  {
    id: "audio-6",
    title: "Ye",
    artist: "Burna Boy",
    artwork:
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=400",
    uses: 387000,
    duration: "3:39",
    trending: true,
  },
];

const placeResults = [
  {
    id: "place-1",
    name: "Buea",
    location: "South-West, Cameroon",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?w=700",
    posts: 18200,
    trending: true,
  },
  {
    id: "place-2",
    name: "Douala",
    location: "Littoral, Cameroon",
    image: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=700",
    posts: 42700,
    trending: true,
  },
  {
    id: "place-3",
    name: "Yaoundé",
    location: "Centre, Cameroon",
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=700",
    posts: 39400,
    trending: true,
  },
  {
    id: "place-4",
    name: "Limbe",
    location: "South-West, Cameroon",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700",
    posts: 12600,
    trending: false,
  },
  {
    id: "place-5",
    name: "Kribi",
    location: "South, Cameroon",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?w=700",
    posts: 9800,
    trending: false,
  },
  {
    id: "place-6",
    name: "Lagos",
    location: "Nigeria",
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=700",
    posts: 86200,
    trending: true,
  },
];

const hashtagResults = [
  {
    id: "hashtag-1",
    title: "#Cameroon",
    posts: 128000,
    trending: true,
  },
  {
    id: "hashtag-2",
    title: "#Afrobeats",
    posts: 94800,
    trending: true,
  },
  {
    id: "hashtag-3",
    title: "#Football",
    posts: 87200,
    trending: true,
  },
  {
    id: "hashtag-4",
    title: "#Technology",
    posts: 61400,
    trending: true,
  },
  {
    id: "hashtag-5",
    title: "#Fashion",
    posts: 53800,
    trending: false,
  },
  {
    id: "hashtag-6",
    title: "#Travel",
    posts: 48200,
    trending: false,
  },
  {
    id: "hashtag-7",
    title: "#Music",
    posts: 43700,
    trending: true,
  },
  {
    id: "hashtag-8",
    title: "#Gists",
    posts: 39600,
    trending: true,
  },
];

const trendingGists = [
  {
    id: "trend-1",
    title: "Tech is changing how we connect",
    username: "techwithjames",
    userId: "user-2",
    avatar: "https://i.pravatar.cc/150?img=12",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=900",
    likes: 8400,
    comments: 421,
    reposts: 182,
    category: "Technology",
    rank: 1,
    time: "12 min ago",
  },
  {
    id: "trend-2",
    title: "The weekend in Buea",
    username: "travelwithsophie",
    userId: "user-1",
    avatar: "https://i.pravatar.cc/150?img=44",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?w=900",
    likes: 6900,
    comments: 318,
    reposts: 142,
    category: "Travel",
    rank: 2,
    time: "24 min ago",
  },
  {
    id: "trend-3",
    title: "Cameroon football is alive!",
    username: "danielw",
    userId: "user-4",
    avatar: "https://i.pravatar.cc/150?img=53",
    image: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=900",
    likes: 11200,
    comments: 687,
    reposts: 391,
    category: "Football",
    rank: 3,
    time: "36 min ago",
  },
  {
    id: "trend-4",
    title: "New fashion trends everyone is talking about",
    username: "oliviam",
    userId: "user-3",
    avatar: "https://i.pravatar.cc/150?img=47",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900",
    likes: 5700,
    comments: 294,
    reposts: 118,
    category: "Fashion",
    rank: 4,
    time: "48 min ago",
  },
  {
    id: "trend-5",
    title: "Afrobeats is taking over the world",
    username: "emmad",
    userId: "user-7",
    avatar: "https://i.pravatar.cc/150?img=32",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=900",
    likes: 15400,
    comments: 921,
    reposts: 604,
    category: "Music",
    rank: 5,
    time: "1 hr ago",
  },
  {
    id: "trend-6",
    title: "Simple ideas that make life better",
    username: "alexj",
    userId: "user-8",
    avatar: "https://i.pravatar.cc/150?img=14",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=900",
    likes: 4300,
    comments: 207,
    reposts: 91,
    category: "Lifestyle",
    rank: 6,
    time: "2 hrs ago",
  },
];

const discoverPosts = [
  {
    id: "discover-post-1",
    user: {
      id: "creator-1",
      name: "Marcus Thompson",
      username: "marcust",
      avatar: "https://i.pravatar.cc/150?img=11",
      verified: true,
    },
    caption: "Sometimes the best ideas happen when you simply slow down.",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800",
    likes: 2800,
    comments: 142,
    reposts: 61,
    category: "Lifestyle",
  },
  {
    id: "discover-post-2",
    user: {
      id: "creator-2",
      name: "Emma Davis",
      username: "emmad",
      avatar: "https://i.pravatar.cc/150?img=32",
      verified: false,
    },
    caption: "A little sunshine, a good coffee, and a fresh perspective.",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=800",
    likes: 1900,
    comments: 96,
    reposts: 43,
    category: "Lifestyle",
  },
  {
    id: "discover-post-3",
    user: {
      id: "creator-3",
      name: "Alex Johnson",
      username: "alexj",
      avatar: "https://i.pravatar.cc/150?img=14",
      verified: true,
    },
    caption: "Exploring new places and collecting moments along the way.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?w=800",
    likes: 3400,
    comments: 181,
    reposts: 82,
    category: "Travel",
  },
  {
    id: "discover-post-4",
    user: {
      id: "creator-4",
      name: "Sarah Williams",
      username: "sarahw",
      avatar: "https://i.pravatar.cc/150?img=47",
      verified: false,
    },
    caption: "Your style is your story. Wear it with confidence.",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800",
    likes: 4100,
    comments: 214,
    reposts: 104,
    category: "Fashion",
  },
  {
    id: "discover-post-5",
    user: {
      id: "creator-5",
      name: "Chris Morgan",
      username: "chrism",
      avatar: "https://i.pravatar.cc/150?img=59",
      verified: true,
    },
    caption: "Building something today that will make tomorrow easier.",
    image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
    likes: 3200,
    comments: 156,
    reposts: 74,
    category: "Technology",
  },
  {
    id: "discover-post-6",
    user: {
      id: "creator-6",
      name: "Mia Thompson",
      username: "miat",
      avatar: "https://i.pravatar.cc/150?img=49",
      verified: false,
    },
    caption: "Good music, good people, and unforgettable memories.",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800",
    likes: 2700,
    comments: 121,
    reposts: 58,
    category: "Music",
  },
  {
    id: "discover-post-7",
    user: {
      id: "creator-7",
      name: "Brian Adams",
      username: "briana",
      avatar: "https://i.pravatar.cc/150?img=68",
      verified: false,
    },
    caption: "Nothing beats a peaceful evening after a busy day.",
    image: "https://images.unsplash.com/photo-1500534623283-312aade485b7?w=800",
    likes: 1800,
    comments: 83,
    reposts: 32,
    category: "Travel",
  },
  {
    id: "discover-post-8",
    user: {
      id: "creator-8",
      name: "Rachel Green",
      username: "rachelg",
      avatar: "https://i.pravatar.cc/150?img=45",
      verified: true,
    },
    caption: "Create more. Compare less. Keep moving forward.",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800",
    likes: 5200,
    comments: 267,
    reposts: 133,
    category: "Motivation",
  },
];

const discoverCategories = [
  {
    id: "accounts",
    label: "Accounts",
    icon: "person-outline",
  },
  {
    id: "audio",
    label: "Audio",
    icon: "musical-notes-outline",
  },
  {
    id: "places",
    label: "Places",
    icon: "location-outline",
  },
  {
    id: "hashtags",
    label: "Hashtags",
    icon: "pricetag-outline",
  },
  {
    id: "trending",
    label: "Trending",
    icon: "flame-outline",
  },
];

const discoverStats = {
  totalAccounts: 842000,
  totalGists: 2400000,
  totalAudio: 185000,
  totalPlaces: 12400,
};

export {
  currentUser,
  recentSearches,
  suggestedUsers,
  audioResults,
  placeResults,
  hashtagResults,
  trendingGists,
  discoverPosts,
  discoverCategories,
  discoverStats,
};

export default {
  currentUser,
  recentSearches,
  suggestedUsers,
  audioResults,
  placeResults,
  hashtagResults,
  trendingGists,
  discoverPosts,
  discoverCategories,
  discoverStats,
};
